.\" A little documentation for future use
.\" This a comment
.\" TH request sets the title of the man page and the section (between 1 and 8)
.\" SH is a primary section heading
.\" TP sets up an indented paragraph with label
.\" B makes text appear in bold face
.\" I makes text appear in italic face
.\" inline versions would look like \fBthis\fR and \fIthis\fR
.\" EX and EE surrounds example section with text as is, with no empty lines in between the actual lines
.TH FREAKYFETCH 1 "{DATE}" "{FREAKYFETCH_VERSION}" "A 𝓯𝓻𝓮𝓪𝓴𝔂 👅💦 system info tool for Linux"
.SH DESCRIPTION
Freakyfetch is a program inspired by neofetch and uwufetch, that takes system information and prints it in terminal in an 𝓯𝓻𝓮𝓪𝓴𝔂 way, with either 𝓯𝓻𝓮𝓪𝓴𝔂 ascii or image logo.
.SH SYNOPSYS
\fBfreakyfetch\fR [\fIOPTIONS\fR] [\fIARGUMENTS\fR]
.SH OPTIONS
.TP
.B -c --config
you can change config path
.TP
.B -h --help
prints the help page
.TP
.B -i --image
prints image instead of ascii logo uses a custom image if one is provided (disabled on iOS)
works in most terminals, read README.md for more info
.TP
.B -l --list
prints a list of all supported distributions
.TP
.B -r --read-cache
reads the cache file (~/.cache/uwufetch.cache)
.TP
.B -v --version
prints the current uwufetch version
.TP
.B -w --write-cache
writes to the cache file (~/.cache/uwufetch.cache)
.SH CONFIGURATION
The system-wide config file is /etc/uwufetch/config, and you can use it to configure uwufetch globally or as a template for your own config.
The user config file is located in $HOME/.config/uwufetch/config (you need to create it), but you can change the path by using the \fB--config\fR option.
.TP
.SH EXAMPLE
.EX
#distro=freaky
#image=~/Pictures/picture.png
user=true
os=true
host=true
kernel=true
cpu=true
gpu=1 # disables the gpu[1] (array goes from 0 to 255)
gpus=true # enables all gpus (except 1 that got disabled before)
ram=true
resolution=false
shell=true
pkgs=true
uptime=true
colors=true
.EE
.SH SUPPORTED DISTRIBUTIONS
Distribution name -d \fBoption\fR
.TP
.SH FULLY SUPPORTED
.EX
Freaky Imposter            \fBamogos\fR
Freakpine                  \fBalpine\fR
Freaky Arch                \fBarch\fR
Freaky Arco                \fBarcolinux\fR
Freaky Artix               \fBartix\fR
Debfreakian                \fBdebian\fR
Freaky Endeavour           \fBendeavour\fR
Freakdora                  \fBfedora\fR
Freaky Gentoo              \fBgentoo\fR
Freaky GUIX                \fBguix\fR
Linux FreakMint            \fBlinuxmint\fR
Freakjaro                  \fBmanjaro\fR
Freakjaro ARM              \fBmanjaro-arm\fR
OpenFreakSUSE              \fBopensuse-leap\fR
Freaky PopOS               \fBpop\fR
Raspfreakian               \fBraspbian\fR
Freayk Slackware           \fBslackware\fR
Freaky solus               \fBsolus\fR
Freakbuntu                 \fBubuntu\fR
Freaky void                \fBvoid\fR
Nyandroid                  \fBandroid\fR
Ultra Freaky               \fBunknown\fR
.EE
.TP
.SH IMAGE OR ASCII ONLY
.EX
Freaky Deepin              \fBdeepin\fR
Freaky Femboy              \fBfemboyos\fR
Freakeon                   \fBneon\fR
Freaky NixOS               \fBnixos\fR
Freaky Xero                \fBxerolinux\fR
Freaky Rocky               \fBrocky\fR
FreakBSD                   \fBfreebsd\fR
Freaky  OpenBSD            \fBopenbsd\fR
Freaky macOS               \fBmacos\fR
Freaky iOS                 \fBios\fR
Freakdows  \fBwindows\fR
.EE
.SH EXAMPLES
.EX
freakyfetch -c ~/.config/example/path_to_config
freakfetch -i some_image.png  # prints custom image (no full path is needed)
.EE
.SH DEPENDENCIES
.TP 8
.B freecolor
ram usage on FreeBSD
.TP
.B libc (required)
glibc on gnu systems or musl on non-gnu systems
.TP
.B viu
print images instead of ascii logo
.TP
.B xwininfo
get screen resolution
.TP
.B lshw
better gpu info
.TP
.B kitty
better image viewing
.P
All of these dependencies are optional. There are no required dependencies (except libc).
.SH LICENSE AND COPYRIGHT
MIT License

Copyright (c) 2024 Leon Cotten

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
