CC=gcc
BUILD_DIR=build
PRIMARY_TARGETS=$(BUILD_DIR)/$(FREAKY_EXECUTABLE) $(BUILD_DIR)/$(FREAKY_IMAGE)
SOURCE_DIR=src
FREAKY_IMAGE=freaky.png
FREAKY_EXECUTABLE=freakyfetch

all: $(BUILD_DIR) $(PRIMARY_TARGETS)

install: $(BUILD_DIR)
	cp $(BUILD_DIR)/* /usr/local/bin

remove: /usr/local/bin/$(FREAKY_EXECUTABLE) /usr/local/bin/$(FREAKY_IMAGE)
	rm /usr/local/bin/$(FREAKY_EXECUTABLE) /usr/local/bin/$(FREAKY_IMAGE)

clean: $(BUILD_DIR)
	rm -rf $(BUILD_DIR)

$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)

$(BUILD_DIR)/$(FREAKY_EXECUTABLE): $(SOURCE_DIR)/main.c | $(BUILD_DIR)
	$(CC) $(SOURCE_DIR)/main.c -o $(BUILD_DIR)/$(FREAKY_EXECUTABLE)

$(BUILD_DIR)/$(FREAKY_IMAGE): $(SOURCE_DIR)/$(FREAKY_IMAGE) | $(BUILD_DIR)
	cp $(SOURCE_DIR)/$(FREAKY_IMAGE) $(BUILD_DIR)
